#!/usr/bin/env python3

__author__ = 'Pavel Polishchuk'

import os
import re
import argparse


def main_params(in_dir, out_dir):

    if not os.path.isdir(out_dir):
        os.mkdir(out_dir)

    p_dock = re.compile("^dock[0-9]*$")
    p_file = re.compile("^best-{0,1}[0-9.]*_.*$")
    dock_dirs = [d for d in os.listdir(in_dir) if os.path.isdir(os.path.join(in_dir, d)) and re.match(p_dock, d)]
    for d in dock_dirs:
        best_score = 1000
        best_pose = ''
        for item in os.listdir(os.path.join(in_dir, d)):
            if os.path.isfile(os.path.join(in_dir, d, item)) and re.match(p_file, item):
                score = float(item.split('_')[0][4:])
                if score < best_score:
                    best_score = score
                    best_pose = item
        out_fname = os.path.join(out_dir, d + '_' + best_pose)
        # remove existed links
        try:
            os.unlink(out_fname)
        except FileNotFoundError:
            pass
        os.symlink(os.path.abspath(os.path.join(in_dir, d, best_pose)), out_fname)


def main():
    parser = argparse.ArgumentParser(description='Get best poses from S4MPLE docking and store in a separate dir. '
                                                 'Before run scripts poses should be generated by S4MpLE as described '
                                                 'in the manual.')
    parser.add_argument('-i', '--input_dir', metavar='', required=True,
                        help='dir path with ligands and dock subdirs with results and generated ligand poses.')
    parser.add_argument('-o', '--output_dir', metavar='', required=True,
                        help='dir to store best poses.')

    args = vars(parser.parse_args())
    for o, v in args.items():
        if o == "input_dir": in_dir = v
        if o == "output_dir": out_dir = v

    main_params(in_dir, out_dir)


if __name__ == '__main__':
    main()
